### ISSUE TITLE
List of bugs and suggestions that I found while using AlphaHack v2 (And this issue is first issue report on here lol)

### ISSUE THREAD

**Issue by Johnmacrocraft** [ArceusMatt/AlphaHack-v2#3]
_-List of bugs_
(Skipping ModPE will be disabled ~ message bug, you even already know that!)
1. When you enable Auto destroy, leave that menu and reopen instead of Auto destory Auto spam looks as enabled. You can still disable it by tapping Auto destroy. Also, It seems Server.getAddress to block spawning destoryed blocks doesn't work.
2. Tapping Add Exp button in enchant menu will result game crash.
_There might be more bugs from me or others!_
_-List of suggestions_
1. Use putting fire block instead of putting nether portal block on Nether Portal menu; Creating nether portal using obsidian and portal block will result game create new portal when you went to nether using newly created (by AlphaHack) and go back, because creating portal without flint and steel (fire block) is invaild. Unlike TNT, nether portal can also created using fire block. If you make vaild obsidian nether portal frame and put fire block inside it it'll create nether portal **as well**.
2. No Korean translation, I suggested it and even you put my contribution in credits menu as _Adding Korean translation and blockprotect._ If you're not adding it because of some reason, I hope it would get added soon as if you can.
_There might be more suggestions from me or others!_

**Comment by ArceusMatt** [comment]
Fire being spawned in a server makes it invalid and the fire won't create the nether portal but i will add an option to use either fire or nether block.
Add exp fixed, crash; undefined function is now defined.
Korean translation won't be added till v2 is complete.
https://github.com/ArceusMatt/AlphaHack-v2/commit/340aabc44db80977dfa9e64a77f45c0e386a111a
